# Generated by Django 4.1.4 on 2023-05-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('type', models.CharField(max_length=10)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.TextField()),
                ('schedule', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('files', models.ImageField(upload_to='')),
                ('moderator', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('sub_category', models.CharField(max_length=20)),
                ('rigor_rank', models.IntegerField()),
                ('attendees', models.JSONField()),
            ],
        ),
    ]
