# Generated by Django 4.1.4 on 2023-05-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='attendees',
        ),
        migrations.AlterField(
            model_name='app',
            name='schedule',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
